package com.bci.harness.dataimport.service;

import com.bci.harness.message.entity.Message;
import com.bci.harness.message.service.MessageService;
import com.bci.harness.victim.entity.Victim;
import com.bci.harness.victim.service.VictimService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class DataImportServiceImpl implements DataImportService {
    private MessageService insultService;
    private VictimService victimService;

    private static final Logger LOGGER = LoggerFactory.getLogger(DataImportService.class);

    public DataImportServiceImpl(MessageService insultService, VictimService victimService) {
        this.insultService = insultService;
        this.victimService = victimService;
    }

    @Override
    public void importData() {
        if (insultService.getInsultCount() == 0 && victimService.getVictimCount() == 0) {
            List<Message> messages = new ArrayList<>();
            LOGGER.info("Importing data");
            // Real-world insults/threats that a real victim has to listen to. The suspected agent who says them is Raul.
            Message message1 = new Message();
            message1.setContent("Zabiju tě ani nebudeš vědět jak.");
            messages.add(message1);

            Message message2 = new Message();
            message2.setContent("Dostaneš takovou sodu, že se posereš.");
            messages.add(message2);

            Message message3 = new Message();
            message3.setContent("Zabiju tě jednou ranou.");
            messages.add(message3);

            Message message4 = new Message();
            message4.setContent("Rozluč se se životem.");
            messages.add(message4);

            Message message5 = new Message();
            message5.setContent("Dostaneš sodu."); // refers to "Česká soda" TV series
            messages.add(message5);                 // that Raul watched already in mid 90s.
            // I don't watch because it's disgusting.

            Message message6 = new Message();
            message6.setContent("To je síla.");
            messages.add(message6);

            Message message7 = new Message();
            message7.setContent("Podřežu tě, jestli budeš takhle chytrej.");
            messages.add(message7);

            Message message8 = new Message();
            message8.setContent("Za chvíli tam na tebe vlítnu.");
            messages.add(message8);

            Message message9 = new Message();
            message9.setContent("Si tam dojdu pro tebe.");
            messages.add(message9);
            // Note: Miroslav K. also told me that when he started working on the Harness
            //       project to unite the victims, the insults stopped and
            //       he only heard threats from Raul from then onward. It's the same here.
            //       This project can catch Raul and other similar agents
            //       by uniting the victims who hear the same messages (insults, threats, etc).

            insultService.saveAll(messages);

            Victim victim = new Victim();
            victim.setUsername("user");
            victim.setPassword("123456");
            victim.setEmail("autogenerated@dont.reply");
            victim.setMessages(messages);
            victimService.save(victim);
        }
    }
}
