<?php

/**
 * Initial data import when message and victim tables are both empty.
 * PHP counterpart of Java com.bci.harness.dataimport.service.DataImportServiceImpl:
 * demo lines (real-world threats/insults a victim heard; suspected source “Raul”) plus username `user`.
 *
 * “Dostaneš sodu.” refers to the “Česká soda” TV series Raul watched in the mid-90s.
 * When Miroslav K. worked on uniting victims via Harness, the insults stopped and only threats
 * from Raul remained—the same idea applies here: matching lines can surface agents like Raul.
 */
class SeedService
{
    private $messages;
    private $victims;

    public function __construct($messages, $victims)
    {
        $this->messages = $messages;
        $this->victims = $victims;
    }

    public function runIfEmpty()
    {
        if ($this->messages->count() > 0 || $this->victims->count() > 0) {
            return;
        }

        $contents = [
            'Zabiju tě ani nebudeš vědět jak.',
            'Dostaneš takovou sodu, že se posereš.',
            'Zabiju tě jednou ranou.',
            'Rozluč se se životem.',
            'Dostaneš sodu.', // Česká soda (TV); see class docblock
            'To je síla.',
            'Podřežu tě, jestli budeš takhle chytrej.',
            'Za chvíli tam na tebe vlítnu.',
            'Si tam dojdu pro tebe.',
        ];

        $this->messages->insertManyIgnoringDuplicates($contents);

        $hash = password_hash('123456', PASSWORD_BCRYPT);
        $id = $this->victims->insert('user', $hash, 'autogenerated@dont.reply');
        $this->victims->linkVictimToMessagesByContent($id, $contents);
    }
}
